### ISSUE TITLE
Coefficient of variation violin plots

### ISSUE THREAD

**Issue by ethanweinberger** [YosefLab/scvi-criticism#21]
### Description of feature

Hi! First of all, thank you for the great package. It's been super useful for evaluating some models that I've been prototyping recently.

I think it would be great to have a method in the `PPCPlot` class for producing coefficient of variation violin plots similar to [Extended Data Fig. 1a](https://www.nature.com/articles/s41592-020-01050-x/figures/6) from the totalVI paper to easily compare performance across models. 

I've written up some matplotlib code for producing these plots (see below for an example) and would be happy to open a PR to get this in. Perhaps this could be added as an option to the `plot_cv` function (similar to the `plot_kind` parameter for `plot_diff_exp`)?

![image](https://user-images.githubusercontent.com/7200040/216729458-739d23d0-8a96-4463-bc31-88dfb2098acc.png)

**Comment by watiss** [comment]
Definitely! Please feel free to create a PR. And thanks!
We're doing a bit of refactoring ([pr](https://github.com/YosefLab/scvi-criticism/pull/23)) so maybe wait till that goes in to avoid annoying merge conflicts.

**Comment by ethanweinberger** [comment]
Sounds good! I'll wait for the refactoring to be merged in then I'll open a new PR.

**Comment by watiss** [comment]
Hi Ethan. This package is now merged into the scvi-tools package (see this [PR](https://github.com/scverse/scvi-tools/pull/2058)) and you can directly use it from there. We've removed the generic plotting utilities for now. We'll give some plotting examples in scvi tutorials (upcoming) but otherwise will leave the freedom to end users to use their custom plotting for their specific use case(s).
Thanks for using this tool and please leave any future feedback in scvi [issues](https://github.com/scverse/scvi-tools/issues) as this repo will be going away.
